name: check cache

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/bla
          key: test2
      - run: ls -lR
