name: main artifact

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: create artifact
        run: |
          echo "echo 123" > artifact.sh
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact.sh
