name: download artifact

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: some_workflow.yml
          name: artifact2
      - name: run artifact
        run: |
          ls -l
          chmod +x ./artifact.sh
          ./artifact.sh
