name: main artifact

on: [push]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: some_workflow.yml
          name: artifact
      - name: run artifact
        run: |
          chmod +x artifact
          ./artifact
